[[questions]]
question = "When was the first known use of the word 'quiz'"
answer = "1781"
alternatives = ["1771", "1871", "1881"]

[[questions]]
question = "Which built-in function can get information from the user"
answer = "input"
alternatives = ["get", "print", "write"]

[[questions]]
question = "Which keyword do you use to loop over a given list of elements"
answer = "for"
alternatives = ["while", "each", "loop"]

[[questions]]
question = "What's the purpose of the built-in zip() function"
answer = "To iterate over two or more sequences at the same time"
alternatives = [
    "To combine several strings into one",
    "To compress several files into one archive",
    "To get information from the user"
]

[[questions]]
question = "What's the name of Python's sorting algorithm"
answer = "Timsort"
alternatives = ["Quicksort", "Merge sort", "Bubble sort"]

[[questions]]
question = "What does dict.get(key) return if key isn't found in dict"
answer = "None"
alternatives = ["key", "True", "False"]

[[questions]]
question = "What's the official name of the := operator"
answer = "Assignment expression"
alternatives = [
    "Named expression",
    "Walrus operator",
    "Colon equals operator"
]